// Illustrative placeholders, never instructions to execute a write automatically.
export const examples = {
  list_sensitivity_labels: { limit: 25 },
  get_sensitivity_label: { label_id: "Example-Label" },
  get_label_policy_settings: {},
  list_label_policies: { limit: 25 },
  get_label_policy: { identity: "Example-Policy" },
  create_sensitivity_label: { name: "Example-Label", display_name: "Example", tooltip: "Example label" },
  set_sensitivity_label: { identity: "Example-Label", display_name: "Example updated" },
  create_label_policy: { name: "Example-Policy", labels: ["Example-Label"], exchange_location: ["example@contoso.com"] },
  set_label_policy: { identity: "Example-Policy", comment: "Example update" },
  remove_sensitivity_label: { identity: "Example-Label", confirm: true },
  remove_label_policy: { identity: "Example-Policy", confirm: true },
  list_dlp_policies: { workload: "SharePoint", limit: 25 },
  get_dlp_policy: { identity: "Example-Policy" },
  list_dlp_rules: { policy: "Example-Policy", limit: 25 },
  get_dlp_rule: { policy: "Example-Policy", limit: 25 },
  create_dlp_policy: { name: "Example-Policy" },
  set_dlp_policy: { identity: "Example-Policy", comment: "Example update" },
  create_dlp_rule: { name: "Example-Rule", policy: "Example-Policy" },
  set_dlp_rule: { identity: "Example-Rule", report_severity_level: "High" },
  remove_dlp_policy: { identity: "Example-Policy", confirm: true },
  remove_dlp_rule: { identity: "Example-Rule", confirm: true },
  create_endpoint_dlp_policy: { name: "Example-Endpoint-Policy" },
  create_endpoint_dlp_rule: { name: "Example-Rule", policy: "Example-Endpoint-Policy", endpoint_restrictions: [{ activity: "Print", action: "Audit" }] },
  create_copilot_dlp_policy: { name: "Example-Copilot-Policy" },
  create_copilot_dlp_rule: { name: "Example-Rule", policy: "Example-Copilot-Policy", sensitive_information_types: ["Credit Card Number"] },
  list_sensitive_information_types: { scope: "custom", limit: 25 },
  get_auth_status: {},
};
